# Generated by Django 5.0.14 on 2026-09-01 16:59

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=30, validators=[apps.core.validators.validate_phone_with_country_code]),
        ),
    ]
