# Generated by Django 5.0.14 on 2026-08-19 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='benefit_detail',
            field=models.TextField(blank=True, verbose_name='Detalle del beneficio'),
        ),
        migrations.AddField(
            model_name='business',
            name='benefit_type',
            field=models.CharField(blank=True, choices=[('descuento', 'Descuento'), ('envio_gratis', 'Envío gratis'), ('promocion', 'Promoción'), ('precio_especial', 'Precio especial'), ('beneficio_exclusivo', 'Beneficio exclusivo'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo de beneficio'),
        ),
        migrations.AddField(
            model_name='business',
            name='home_delivery',
            field=models.BooleanField(default=False, verbose_name='¿Ofrece domicilio?'),
        ),
        migrations.AddField(
            model_name='business',
            name='is_mama_tribu',
            field=models.BooleanField(default=False, verbose_name='¿Emprendimiento de mamá tribu?'),
        ),
        migrations.AddField(
            model_name='business',
            name='responsible_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='business',
            name='tribe_benefit',
            field=models.BooleanField(default=False, verbose_name='¿Tiene beneficio tribu?'),
        ),
        migrations.AddField(
            model_name='business',
            name='tribe_recommended',
            field=models.BooleanField(default=False, verbose_name='¿Recomendado por la tribu?'),
        ),
    ]
